### ISSUE TITLE
New colorless mana symbol

### ISSUE THREAD

**Issue by AlexandreArpin** [AlexandreArpin/mtg-font#10]

**Comment by raven-worx** [comment]
unfortunately this fix breaks backward compatibility with existing CSS styles

**Comment by AlexandreArpin** [comment]
Hey! Thanks for your input.

I try to follow the standard used by Gatherer and mtgjson for Oracle text and trump short and easy to use class names over backward compatibility as this point in the project. Using `mi-c` for Chaos was a mistake as it should have been `mi-chaos` from the beginning.

Would this had been released previously, I would have made a major revision for it and probably made a minor revision update with backward compatibility.

If breaking backward compatibility is a major issue for you or anyone, let me know and I'll gladly branch a backward compatible version for those who need it.
