### ISSUE TITLE
Attack and defense

### ISSUE THREAD

**Issue by AckerApple** [AlexandreArpin/mtg-font#12]
Please add new attack and defense icons for Arena of Planeswalkers. People, including myself, are building custom cards and you have all the icons but those two. Thank you in advanced, excellent craftsmanship on these icons you made!

http://i0.wp.com/geekdad.com/wp-content/uploads/2015/07/MTG-Arena-of-the-Planeswalkers-game-Planeswalkers-cards.jpg

**Comment by AlexandreArpin** [comment]
Hey! Thanks for submitting an issue.

The main focus of this font is for the Magic the Gathering Collectible Card Game, branching out to support other Magic products isn't what I have in mind at the moment.

These two icons seems very specific to Arena of the Planeswalkers and therefore will not be included. 

If you wish, you can fork the project to add icons from Arena of the Planeswalker. All of the SVG used to create the font are available, you would simply need to add the attack and defense vector icons.

**Comment by AckerApple** [comment]
I may fork. Thank you for suggesting

How might I persuade you to do??? I intended to make an HTML5 based custom card maker for the Arena of Planeswalkers game.

Have you played the Arena of Planeswalkers game? I grew up, now 33, on MTG cards and still have em all. I have come to absolutely love the board game and think it has tons of "untapped" potential.


Please reconsider. Thank you kindly in advanced.

_AA

**Comment by AckerApple** [comment]
Thanks for the push. Please review [mtg-aotp-syms](https://github.com/AckerApple/mtg-aotp-syms)
