### ISSUE TITLE
Planeswalk Symbol

### ISSUE THREAD

**Issue by chryton** [AlexandreArpin/mtg-font#8]
Image: http://fc02.deviantart.net/fs70/i/2013/181/2/3/planeswalker_symbol_by_drdraze-d6b8ml7.png

http://archive.wizards.com/Magic/magazine/article.aspx?x=mtg/daily/feature/51

Seen on the Planechase die. Also a general symbol for planeswalkers and MtG.

**Comment by AlexandreArpin** [comment]
Done! Thanks for filling a ticket!
